import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import AllProgs from "./ui/all-progs";
import { fetchAllPrograms } from "./lib/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Program Dashboard",
  description: "Generated by Ishan",
};

export default async function RootLayout({ children }) {
  const progs = await fetchAllPrograms();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <Navbar />
          <div className="flex ">
            <div className="w-1/4 hidden lg:block border-r-2 border-gray-400 ">
              <AllProgs progs={progs} />
            </div>
            <div className="lg:w-3/4 w-full items-center">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
